# Generated by Django 4.0.4 on 2022-10-12 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appblogs', '0002_blog_uid_post_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Blog_relacionado', to='appblogs.blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='lista_posts', to='appblogs.post'),
        ),
    ]
