# Generated by Django 4.0.4 on 2022-10-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblogs', '0003_post_blog_alter_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='e_resposta',
            field=models.BooleanField(default=True, verbose_name='É uma resposta'),
        ),
    ]
