# Generated by Django 4.0.4 on 2022-10-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblogs', '0004_resposta_e_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='e_resposta',
        ),
        migrations.AddField(
            model_name='comentario',
            name='e_resposta',
            field=models.BooleanField(default=False, verbose_name='É uma resposta'),
        ),
    ]
