# Generated by Django 4.0.4 on 2022-10-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblogs', '0005_remove_resposta_e_resposta_comentario_e_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tema',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tema do POST'),
        ),
    ]
